name: 'CI Tools Bun'
description: 'Build and push using ci-tools'
inputs:
  app-name:
    description: 'Name of the application to build and push'
    required: true
  sonar-active:
    description: 'Enable SonarQube analysis'
    default: 'false'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true
  github-run-number:
    description: 'GitHub run number for versioning'
    default: ${{ github.run_number }}
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Get ci-tools script
      shell: bash
      run: wget https://raw.githubusercontent.com/auctelia/ci-tools/master/ci.sh

    - name: Make ci-tools runnable
      shell: bash
      run: chmod +x ./ci.sh

    - name: Run ci-tools
      shell: bash
      run: ./ci.sh go --sonarqube=${{inputs.sonar-active}} --app-name=${{ inputs.app-name }} --docker-username=${{ github.actor }}  --docker-password=${{ inputs.github-token }} --version-number=${{inputs.github-run-number}} --docker-registry=ghcr.io
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
